bridge:
  ros__parameters:
    # topics and namespaces
    ego_odom_topic: '/odom'
    ego_opp_odom_topic: 'opp_odom'
    ego_drive_topic: 'drive'
    collision_topic: 'collision_event'

    # map parameters
    map_path: '/sim_ws/src/f1tenth_gym_ros/maps/levine'

    # opponent parameters
    num_agent: 1

    dt: 0.002
    mass: 1.0

    # ego starting pose on map
    starting_position: [5.0, 5.0, 1.0]
    starting_orientation: [0.0, 0.0, 0.0, 1.0]

    gate_1_position: [1.0, 2.0, 5.0]
    gate_1_orientation: [0.0, 0.0, 0.0, 1.0]

    gate_2_position: [3.0, 5.0, 1.0]
    gate_2_orientation: [0.0, 0.707, 0.0, 0.707]

    gate_3_position: [6.0, 5.0, 1.0]
    gate_3_orientation: [0.0, 0.0, 0.707, 0.707]

    # teleop
    kb_teleop: True
